Модуляция
htmlacademy-javascript/1706423-keksobooking-23 pull request #4
Opened 2021-06-14 18:27 UTC by faleen88

2021-06-14 18:52 UTC, ademaro commented on js/data.js
> +    (index < 10) ? image = `img/avatars/user0${index}.png` : image = `img/avatars/user${index}.png`;
```js
const image = (index < 10) ? `img/avatars/user0${index}.png` : `img/avatars/user${index}.png`;
```

2021-06-14 18:53 UTC, ademaro commented on js/data.js
> +}
не очень удачный вариант, подумай как индекс массива передавать, например

2021-06-14 18:54 UTC, ademaro commented on js/data.js
> +function getArrayAdvertisements() {
предлагаю SIMILAR_ADVERTISEMENT_QUANTITY сделать параметром

2021-06-14 18:56 UTC, ademaro commented on js/data.js
> +function getArrayAdvertisements() {
Слово Array можно убрать из названия

2021-06-14 18:57 UTC, ademaro commented on js/data.js
> +getArrayAdvertisements();
Нужно не вызывать, а проэкспортировать, вызывать будем в main.js

2021-06-14 18:57 UTC, ademaro commented on js/main.js
> +import './util.js';
util.js нам тут не нужен, убираем строчку

2021-06-14 18:57 UTC, ademaro requested changes
Давай поправим немного, закрою ПР

2021-06-15 07:23 UTC, faleen88 commented
SIMILAR_ADVERTISEMENTS_QUANTITY лучше экспортировать или объявлять в main.js?

2021-06-15 21:47 UTC, ademaro commented on js/main.js
> +getAdvertisements(SIMILAR_ADVERTISEMENTS_QUANTITY);
👍🏼

2021-06-15 21:47 UTC, ademaro approved these changes
Отлично! Летим дальше 🚀

2021-06-15 21:47 UTC, merged